### ISSUE TITLE
Replace password hashes with private prompt

### ISSUE THREAD

**Issue by tilsammans** [al3x/sovereign#137]
See the docs http://docs.ansible.com/playbooks_prompts.html

I believe that Passlib also provides SHA-256 Crypt and we can replace the hashes currently in the script with a private `vars_prompt`. SHA-256 Crypt is pretty good but it's still best practice to not store the hash I think.

When using `vars_prompt` we will have to leave the existing email accounts alone.

**Comment by al3x** [comment]
People seem to have accepted generating and storing hashes in their config files. Closing.

**Comment by spk** [comment]
Using http://docs.ansible.com/playbooks_vault.html or git-crypt, maybe add this projects to the README?
