### ISSUE TITLE
Adding SIP telephony

### ISSUE THREAD

**Issue by neuhaus** [al3x/sovereign#258]
What do you think about adding a SIP server to this project? That way the users would get a SIP address like username@mydomain.com and whenever they do (possibly encrypted) VoIP calls via SIP to other users, the meta data for their end of the call remains on their own server.

That way the sovereign project could supply a decentralized alternative to OStel (https://dev.guardianproject.info/projects/ostel/wiki ).

If you are open to the idea I could start working on it.

**Comment by simontretter** [comment]
There is an interesting cookbook: https://guardianproject.info/wiki/OSTN_cookbook

**Comment by al3x** [comment]
Open to a PR, as with any additional service, but closing this for now out of lack of interest/momentum.
