### ISSUE TITLE
Automate setting of DNS records

### ISSUE THREAD

**Issue by ariddell** [al3x/sovereign#277]
The folks behind edx/configuration provide CloudFormation rules that specify the infrastructure. This seems like the right approach, especially if there's a platform-neutral way to do it (maybe [Terraform](http://www.terraform.io/)). Given how important DKIM and SPF settings are to the core functionality of sovereign, it seems like it would be great if there were a way to automate setting those values in DNS.

**Comment by al3x** [comment]
This is a great suggestion that doesn't seem to have an easy platform-neutral solution to implement. The necessary DNS records are written to files for DKIM, at least.
