### ISSUE TITLE
Ubuntu 14.04 fail2ban dovecot needs to use /var/log/mail.log not /var/log/maillog

### ISSUE THREAD

**Issue by ariddell** [al3x/sovereign#331]
I believe I have this right -- and I'll submit a patch if I do -- but perhaps someone else running Ubuntu 14.04 can confirm.

The `dovecot-pop3imap` section of `/etc/fail2ban/jail.local` has:

```
logpath = /var/log/maillog
```

On Ubuntu 14.04 (and possibly Jessie?) the relevant log file is ``/var/log/mail.log`` (with period).

**Comment by al3x** [comment]
@mariusv I'd really like to merge your PR. Would you mind adding the conditional logic to the existing template?

**Comment by mariusv** [comment]
@al3x , yep..sorry, I was a bit bussy. Done..removed duplicated template and added logic for Ubuntu as in my tests all Ubuntu have the same path

**Comment by al3x** [comment]
:tada:
