### ISSUE TITLE
Apache HTTP-HTTPS redirect not always followed

### ISSUE THREAD

**Issue by stevelord** [al3x/sovereign#334]
Hi,

I've set up my site on a version of sovereign but have noticed that the HTTP - HTTPS redirect in apache isn't always followed by some devices (most notably IOS and Android). The culprit is in roles/blog/templates/etc_apache2_sites_available_blog.j2.

I replaced the rewrite rule with the following and it all works now:

    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

Just thought I'd let everyone know.

**Comment by al3x** [comment]
@stevelord A PR with this change would be much appreciated.

**Comment by neuhaus** [comment]
Before this change is merged, could we have at least one concrete example of a client that has an issue with it?
*Works for me* on *iOS 7.1.2* (I can test more software if you tell me which one has this issue).

**Comment by neuhaus** [comment]
To examine this issue, I configured two apache virtual hosts using this configuration:

    <VirtualHost *:80>
    	ServerName test1.example
    	Redirect permanent / https://test1.example
    </VirtualHost>
    
    <VirtualHost *:80>
    	ServerName test2.example
    	RewriteEngine On
    	RewriteCond %{HTTPS} off
    	RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
    </VirtualHost>

Here's what the HTTP requests look like, with headers. 
First, the permanent redirect version:

    $ curl -i -H "Host: test1.example" localhost:80
    HTTP/1.1 301 Moved Permanently
    Date: Thu, 15 Jan 2015 18:16:58 GMT
    Server: Apache/2.4.7 (Ubuntu)
    Location: https://test1.example
    Content-Length: 307
    Content-Type: text/html; charset=iso-8859-1
    
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html><head>
    <title>301 Moved Permanently</title>
    </head><body>
    <h1>Moved Permanently</h1>
    <p>The document has moved <a href="https://test1.example">here</a>.</p>
    <hr>
    <address>Apache/2.4.7 (Ubuntu) Server at test1.example Port 80</address>
    </body></html>

And here is the redirect using `mod_rewrite`:

    $ curl -i -H "Host: test2.example" localhost:80
    HTTP/1.1 302 Found
    Date: Thu, 15 Jan 2015 18:17:05 GMT
    Server: Apache/2.4.7 (Ubuntu)
    Location: https://test2.example/
    Content-Length: 284
    Content-Type: text/html; charset=iso-8859-1
    
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html><head>
    <title>302 Found</title>
    </head><body>
    <h1>Found</h1>
    <p>The document has moved <a href="https://test2.example/">here</a>.</p>
    <hr>
    <address>Apache/2.4.7 (Ubuntu) Server at test2.example Port 80</address>
    </body></html>

Code 301 (permanent redirect) is semantically correct, 302 is a *temporary redirect* which is not what we want. I don't see any reason why any client would have a problem with a 301 redirect. They are used all over the web. This change should **not** be merged.

**Comment by al3x** [comment]
Agreed. Thanks for reviewing, @neuhaus.

**Comment by neuhaus** [comment]
OK, one thing I noticed is that it's important to have a trailing slash, i.e.
        Redirect permanent / https://test1.example/

If you omit the slash, visiting the url `http://test1.example/foo` will redirect to
`https://test1.examplefoo`. With a trailing slash the redirect will go to `https://test1.example/foo`, which is better.
