### ISSUE TITLE
Switch to domain.com/service instead of subdomains to avoid need of wildcard SSL cert

### ISSUE THREAD

**Issue by alexjj** [al3x/sovereign#335]
One can get a free SSL cert from https://www.startssl.com/, but it only gives one subdomain. However, if services were switched to domain.com/mail and domain.com/news etc. then the certificate could be used.

**Comment by fengor** [comment]
you can get wildcart certs from cacert.org

**Comment by alexjj** [comment]
cacert is a great service but until it's part of mainstream browsers I might as well just use a self-signed one.

**Comment by al3x** [comment]
Please reopen if there's a good solution to doing subdirectories instead of subdomains with Apache.
