### ISSUE TITLE
Selfoss "an error occured"

### ISSUE THREAD

**Issue by reedlaw** [al3x/sovereign#337]
Does anyone get this error after logging in recently? I've checked the db connection and the logs but I can't find anything wrong. There's not much documentation or other ways to troubleshoot that I am aware of.

**Comment by ventolin** [comment]
Yes I've been getting this too but haven't figured out the problem yet.

**Comment by reedlaw** [comment]
@ventolin, thanks! I was able to fix mine by going into the `psql` console and executing the following:

    alter table sources add column filter TEXT;

There should be a migration for this but I'm satisfied with this fix. Hopefully others will find this issue.

**Comment by simontretter** [comment]
I am having this problem right now with the most recent selfoss version. Your fix does not help.

**Comment by reedlaw** [comment]
@simontretter  that worked for me but you can avoid chaging the authentication method by connecting as follows:
`psql -h 127.0.0.1 -U selfoss selfoss`
and use the password from `vars/user.yml`.

**Comment by simontretter** [comment]
Same issue now upgrading from 2.15 to 2.16. Dropping the filter column doesn't solve it this time.
