### ISSUE TITLE
Roundcube Owncloud Carddav Sync Issues

### ISSUE THREAD

**Issue by balajisivaraman** [al3x/sovereign#344]
Hi, I'm not sure whether I'm doing something wrong here, or there's something up with my setup, but Roundcube is ridiculously slow with syncing contacts to the Address Book from my Owncloud carddav.

This is my setup:

VPS: Digital Ocean Debian 7 VM
Roundcube Version: 0.9.x from the Wheezy Backports recent commit.
Owncloud: 7.0.4
CardDav URL: https://cloud(dot)(domain)(dot)com/remote.php/carddav/addressbooks/(OC Username)/contacts

Here's what I did: I copied the Owncloud CardDav URL, went to Roundcube Settings -> CardDav and added a new Address Book with that URL. Initially, I set the sync frequency to every 1 hour, but beyond importing the first contact, Roundcube did nothing. I changed the frequency to every 1 minute with the same result as well.

It's been two days and Roundcube has now imported about 15 contacts. It is still happening. It doesn't stop, but I have no idea what this issue is. Deleting the address book and re-adding it also doesn't help.

To confirm whether it wasn't an issue with my Owncloud server, I setup CardDav syncing with my Nokia Lumia 720 running Windows Phone 8.1 through the ICloud account hack. It synced everything up immediately. It doesn't have any issues syncing up changes I make either way as well.

EDIT: I can't see anything suspicious in the logs as well. No error gets written to roundcube/errors.log, which tells me everything is functioning normally.

Any help would be greatly appreciated?

**Comment by al3x** [comment]
I do not personally use Roundcube with my Sovereign deployment, so I haven't run into this issue. If you have any updates please let us know.

**Comment by norm2k** [comment]
For Roundcube, I use:
https://cloud(dot)(domain)(dot)com:443/remote.php/carddav/addressbooks/(OC Username)/contacts/
and it works just fine.
For my iPhone, however, I use:
https://cloud(dot)(domain)(dot)com/remote.php/carddav/principals/(OC Username)/
and it works just fine
Don't know if it helps but this is what works for me.
Roundcube version 1.1.0
OwnCloud version 8.0.2
(I manually upgraded both)
@al3x Do you use something else for webmail or do you not use webmail at all?
(just curious)

**Comment by al3x** [comment]
@norm2k I just don't use webmail at all. I use native clients on Mac and iOS.

**Comment by balajisivaraman** [comment]
@norm2k, I just upgraded to Owncloud 8.0.2, and it doesn't help, unfortunately. I do use Outlook/Windows Mobile for all my mail, but sometimes I am in the unfortunate position of having to check/respond to my mail through Roundcube. If it's not too much of a trouble, we can just leave this issue open for a while, and I'll try to find some time to figure out what's causing this.
