### ISSUE TITLE
Add bookmark management app (delicious clone)

### ISSUE THREAD

**Issue by silopolis** [al3x/sovereign#346]
Hi,

Having a bookmark management app like https://github.com/sebsauvage/Shaarli aside of Wallabag would be really nice.

Wallabag already supports sharing links to Shaarly (http://doc.wallabag.org/en/Administrator/Hidden_options.html)

Bests

**Comment by al3x** [comment]
Please feel free to submit a pull request for whatever open source services you think would be a welcome addition to Sovereign. However, I would caution that Shaarli does not appear to have been updated in the last year. We try to use actively maintained software for Sovereign, as it's more likely to be secure and reliable.
