### ISSUE TITLE
No external mail

### ISSUE THREAD

**Issue by simontretter** [al3x/sovereign#348]
Current sovereign is broken out of the box on Ubuntu and Debian. Most severe problem ist that no external mail can be received. Dovecot throws no errors. Internal mailing works.

**Comment by tilsammans** [comment]
I'm up to date with my Sovereign install and I can receive external email.

**Comment by simontretter** [comment]
clean install here and a lot of different issues.

**Comment by tilsammans** [comment]
Glad to hear! :+1:
