### ISSUE TITLE
Make use of multiple IP addresses easier

### ISSUE THREAD

**Issue by simontretter** [al3x/sovereign#351]
The current configuration assumes that the VPS/server only has one IP address. For certain usages, it might be interesting to use more than one IP. Can we make this easier? 

The first thing I tried was to add an ipaddr variable that ufw can make use of like this:
ufw: rule=allow port={{ item }} to_ip={{ ipaddr }} proto=tcp

**Comment by al3x** [comment]
For things like firewall rules, you could have users maintain a list of IP addresses associated with their server, then iterate through that list to apply the rules using Ansible's looping constructs. That will work even in the majority use case that only a single IP address is associated with a server.
