### ISSUE TITLE
Multiple Emails

### ISSUE THREAD

**Issue by shaneonabike** [al3x/sovereign#352]
I have read through the documentation but I cannot see how sovereign can be configured for multiple emails easily? Am I missing something or can someone guide me on that process? Is this scalable for many email addresses that someone might want to setup?

**Comment by lukecyca** [comment]
Yes, it can easily handle multiple addresses, aliases, and even multiple mail domains. Just add more elements to the `mail_virtual_*` variables in vars/user.yml and rerun the playbook.

If you're adding more domains for email, you'll want to following the DKIM/SPF setup instructions (located in the README) for each domain.

If this doesn't answer your question, please re-open the issue.

**Comment by shaneonabike** [comment]
Ahhh silly me... after you pointed that out I found this 

mail_virtual_users:
  - account: "{{ main_user_name }}"
    domain: "{{ domain }}"
    password_hash: TODO
    domain_pk_id: 1
#  - account: "{{ TODO }}"
#    domain: "{{ domain }}"
#    password_hash: TODO
#    domain_pk_id: 2

And now realize I can add as many as I want for the same domain as long as I increase the domain_pk_id!

COOL!

**Comment by lukecyca** [comment]
You increment `domain_pk_id` for every new domain you add. You use the same `domain_pk_id` for all addresses under a given domain.

**Comment by shaneonabike** [comment]
Just so that other folks know it's important to remove the brackets... so if you wanted multiple emails you would put

> mail_virtual_users:
>  - account: "{{ main_user_name }}"
>     domain: "{{ domain }}"
>    password_hash: TODO
>    domain_pk_id: 1
>  - account: "user2"
>    domain: "{{ domain }}"
>    password_hash: TODO
>    domain_pk_id: 1

Sorry about the formatting I cannot figure out to make it present properly :/
