### ISSUE TITLE
Option of using Mysql or PostgreSQL

### ISSUE THREAD

**Issue by shaneonabike** [al3x/sovereign#353]
Hey there

Alright so in the installation we are installing postgreSQL but unfortunately for those folks who want to install Drupal it makes life hard (b/c it's not supported that greatly especially with Aegir).

I was wondering if there is an easy way to switch it to MySQL or perhaps a version that I could pull instead?

**Comment by shaneonabike** [comment]
Ok... actually if I see it properly I just need to do a more advanced config right.. Finding all the references to pgsql and replacing that with mysql. Had this been done before and then it was changed to use pgsql.

If so perhaps making a central config for the database type could be good then it allows people more flexibiity?

**Comment by shaneonabike** [comment]
Alright so I just noticed that this was switched in January. For htose that want a quick solution they can follow the clone and checkout before this change was made here https://github.com/al3x/sovereign/pull/129#issuecomment-73799387

I still think it could be good to have the option in the configuration?

**Comment by al3x** [comment]
I'd be open to a pull request that provides the option of MySQL or Postgres. Generally, we've tried to pick a single reasonable default where possible.

**Comment by shaneonabike** [comment]
Sure that sounds great! I prefer not to handle my own version of this... and be able to keep getting updates.... BUT I don't know how to code conditions in ansible.. so I'll need to read into that first before we can proceed... unless you got suggestions

**Comment by shaneonabike** [comment]
BTW I did get this working on my local repo

**Comment by al3x** [comment]
This is a good starting point: http://docs.ansible.com/playbooks_conditionals.html
