### ISSUE TITLE
Turning off SSL for main example.com

### ISSUE THREAD

**Issue by shaneonabike** [al3x/sovereign#355]
Hey there

I am trying to turn off the main SSL for the main site since I am using my own created one and want folks to come to my site without feeling ensecure about accepting my SSL certificate.

Can anyone guide me through how to do that? I've tried several modifications to the apache2 config to no avail!

**Comment by ariddell** [comment]
https://startssl.com/ will give you a free certificate. Soon https://letsencrypt.org/ will as well.

**Comment by shaneonabike** [comment]
Hmm.... but that only works for the main example.com site. So installing that then breaks all the other subdomains like mail.example.com, etc. I am now receiving errors like

NET::ERR_CERT_AUTHORITY_INVALID 

The other certificate that I created myself was a wildcard certificate. Do I need to go through and create one for every subdomain? And how do I do that if I have subdomains that aren't created by this script?

**Comment by shaneonabike** [comment]
I ended up generating one SSL certificate for each site as mentioned. To those trying to figure this out you simply need to do the following

Within each conf file you will need to change the following code.

<code>
    SSLEngine on
    SSLProtocol ALL -SSLv2 -SSLv3
    SSLHonorCipherOrder On
    SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH$
    SSLCertificateFile      /etc/ssl/certs/NEW_SSL_CRT.crt
    SSLCertificateKeyFile   /etc/ssl/private/NEW_SSL_KEY.key
    SSLCACertificateFile    /etc/ssl/certs/COMBINED_INTERMEDIATE_ROOT.pem
</code>

Now if you are using startssl they you can simply modify the existing SSLCACertificate and replacing the wildcard_ca.pem file. This might make your life a little easier.

Also you need to copy all of these files into /etc/ssl/private and /etc/ssl/certs and modify the permissions to match the rest.
