### ISSUE TITLE
Encfs and reboot

### ISSUE THREAD

**Issue by FlorianHeigl** [al3x/sovereign#361]
Hi,

could you add a note about how to proceed after a reboot?
I just added a filesystem for /encrypted (10GB) and found out how to re-mount it with encfs /encrypted /decrypted + passphrase.

So, one reboots the server one needs to do that manually? 
(makes sense to force entering the pw, i get that much)

But after this it seems the daemons have some problem, specifically roundcube won't access some folders any more with a permission issue.

Having an idea how reboot is normally handled would be good. Running on a VPS means sometimes there will be a reboot for external reasons anyway.

**Comment by al3x** [comment]
Yes, you need to enter the password for any encrypted volumes on reboot. This is not Sovereign-specific, but rather a function of how EncFS works.

It is possible that some daemons may need to be restarted after you enter your password for the encrypted volume, as they may have stalled out while looking for resources that will only be available once the volume is decrypted and visible to the daemon user accounts.

**Comment by FlorianHeigl** [comment]
For reference, i.e. #120 pointed at this. it's just annoying that it's nowhere in the docs.

**Comment by whisdol** [comment]
Thanks for adding the section about remounting the encfs-volume to the readme. But I think it would be even more helpful, if the specific command to remount the volume (`encfs /encrypted /decrypted --public`) would be mentioned in this section . I've never worked with encfs before and found it a little counter-intuitive to need to sift through the playbook to find the one command I need to enter after every reboot.
