### ISSUE TITLE
Issue with Debian wheezy, postgresql, and 6265916caa7c2228d506a6cbe530f4348f711f9b

### ISSUE THREAD

**Issue by lbsnrs** [al3x/sovereign#362]
After having pulled the latest changes in sovereign, owncloud' setup fails with 

    TASK: [owncloud | Install dependencies] *************************************** 
    failed: [85.159.212.130] => (item=libapache2-mod-php5,php-apc,python-psycopg2,postgresql-9.3) => {"failed": true, "item": "libapache2-mod-php5,php-apc,python-psycopg2,postgresql-9.3"}
    msg: No package matching 'postgresql-9.3' is available

    FATAL: all hosts have already failed -- aborting

I've checked and there doesn't seem to be a postgresql-9.3 available for wheezy in the repositories configured by the current sovereign setup.

My question is: is postgresql-9.3 actually necessary?

**Comment by al3x** [comment]
Yes, the database is necessary. ownCloud depends on it, but so does our email setup.

**Comment by jplock** [comment]
I think we should downgrade this to 9.1 to stay consistent with the rest of the playbooks.
