### ISSUE TITLE
Blog Apache2 conf

### ISSUE THREAD

**Issue by shaneonabike** [al3x/sovereign#364]
Hey I wanted to point out that the configuration rolled out for the blog is slightly limited. I wanted to suggest a few additions...

Basically, adding the directory index "index.php" as well as some further directory symlink following.

Why? Well after the first install I made these modifications, but then when the server needs to be rebooted I need to rerun playbook which replaces this file. Anyway, this helps most systems that use html and php I think.:)

<code>
    DirectoryIndex          index.html index.php
    Options                 -Indexes

    HostnameLookups         Off

    <Directory />
        Options FollowSymLinks
        AllowOverride All
    </Directory>

    <Directory "/var/www/{{ domain }}/">
        Options FollowSymLinks
        DirectoryIndex index.php
        AllowOverride All
        Require all granted
        Order allow,deny
        Allow from all
    </Directory>
</code>

**Comment by al3x** [comment]
The blog entry is intended for static site generators like Jekyll. If people are installing blogging packages that rely on PHP, like WordPress, they should set up a custom configuration.
