### ISSUE TITLE
Adding new subdomains that are non-SSL

### ISSUE THREAD

**Issue by shaneonabike** [al3x/sovereign#365]
Sorry I realize that this is off topic but I figured maybe someone might be able to help. I added another tool on my server and it is being forced directly to SSL rather than allowing non-SSL.

Is there somewhere that I can configure it to be simply non-SSL or allow both? I can't quite figure out if there is some forced SSL in the configuration files of sovereign.

Thanks heaps
Shane

PS - For the record I didn't buy a wildcard certificate b/c I didn't have the cash and am awaiting the release of the Let's Encrypt everywhere functionality! (ref: https://letsencrypt.org/howitworks/)

**Comment by al3x** [comment]
@shaneonabike Check out, for example: https://github.com/al3x/sovereign/blob/master/roles/git/templates/etc_apache2_sites-available_cgit.j2#L1-L5

You'll find similar sections in the other Apache configuration files used for various services in Sovereign. To get your desired non-SSL, you can move the body of the `<VirtualHost *:443>` block below into the top `<VirtualHost *:80>` section, removing the ` Redirect permanent /` directive. You can delete the SSL-relative directives, of course :)

Not sure what your experience level with this stuff is, but it might be helpful to know that port 443 is used for HTTP over SSL, while port 80 is used for unencrypted HTTP traffic. Wherever you see port 443, that's probably something you'll want to change for your setup. Good luck!

**Comment by shaneonabike** [comment]
Hmm.... that's what I thought too. But in doing so it still tries to use the main certificate and b/c it's not wildcard it never works... super strange. It's like something is redirecting all *.example.com to https...

**Comment by shaneonabike** [comment]
Just in case people tumble upon my post actually what you need to do is disable the apache configuration 00-status.conf. This configuration in sites-enabled actually prevents anything from calling port 80 unless it is internally coming from 127.0.0.1
