### ISSUE TITLE
Can't access SMTP

### ISSUE THREAD

**Issue by miloshadzic** [al3x/sovereign#368]
I’m having trouble setting up sovereign on a blank DigitalOcean droplet. I’m using Debian 7 and I’ve enabled in site.yml only the services that I need but even if I enable all the issue persists.

When the box is set up I can’t connect to the smtp server on neither port 25 nor 465. IMAP works good. What’s even more strange is that I can connect when I am on certain networks like in one coffeshop or using [Cloak](http://getcloak.com) via their Netherlands route.

I’ve also enabled OpenVPN but through it I can’t connect neither to the IMAP nor SMTP ports.

I think it’s a firewall issue but I’m not good familiar enough with ufw/iptables to know how to solve it on my own.

**Comment by al3x** [comment]
So, SMTP works but only on some network connections? Chances are good that your home or work ISP or network administrator is filtering certain types of traffic.

**Comment by miloshadzic** [comment]
Hm I think you're probably right but I'm not sure how to mitigate it. I thought that connecting to the vpn that's on the same host would work but it doesn't (possibly for a different reason though):

```bash
$ telnet mail.rightfold.io 465
Trying 127.0.1.1...
telnet: connect to address 127.0.1.1: Operation timed out
telnet: Unable to connect to remote host
```

The same will happen for port 443 which otherwise works which makes me think this is a different issue.

**Comment by miloshadzic** [comment]
Ok problem 1 was indeed filtering by the ISP. I've never encountered that so I was pretty surprised.

Problem 2 I've solved by editing my ``/etc/hosts`` to be:
```
127.0.0.1 localhost
<actual ip> mail.rightfold.io rightfold.io
```

And now I can fetch email while connected to the VPN. My last question is whether I'm doing something wrong with this change?
