### ISSUE TITLE
Method to adjust aggressiveness of spam filter? (Spam getting through)

### ISSUE THREAD

**Issue by ariddell** [al3x/sovereign#378]
A fair amount of spam is getting through. I've checked the dspam_stats data per #311 and #196 and it is registering when it incorrectly tags spam as ham. Is there a simple way to adjust the aggressiveness? I'd settle for some false negatives at this point.

**Comment by al3x** [comment]
Maybe check out http://www.kirya.net/articles/setting-up-dspam-as-a-filter-for-postfix-on-debian/ ? I'm not sure about a "simple way" to tweak dspam, since it has so many settings.

**Comment by al3x** [comment]
This is probably a better issue to file with dspam, or a post for the dspam mailing list.
