### ISSUE TITLE
Use Docker to contain each application/service

### ISSUE THREAD

**Issue by lukecyca** [al3x/sovereign#99]
Rather than installing each service directly on the machine, we should dockerize some or all of them. This would allow the services to better coexist with other customizations people make on their server.

This may require switching to Ubuntu as the supported distro.

**Comment by al3x** [comment]
"Dockerizing" Sovereign has been discussed a number of times, but there doesn't seem to be much active interest in it. Docker and related container technologies are still a moving target, with competing standards and tools still emerging. It currently doesn't seem like a stable base for a "set it and forget it" personal cloud.

**Comment by neuhaus** [comment]
@denibertovic I started using Docker at work and ran into several severe bugs, I'm glad it's postponed for now. I wouldn't call it anywhere near production ready.

**Comment by qmr** [comment]
I would really love to see this, or something else to isolate / containerize everything.  If a particular service is compromised the exposure would be lessened.

Maybe chroots for some things instead?

**Comment by denibertovic** [comment]
@neuhaus I'm using it everywhere...and haven't had issues.

**Comment by timoc** [comment]
+1
Dockerising (deploying from personal docker registry) should make it easier to manage incremental changes to separate components, and forward migration easier...

**Comment by neuhaus** [comment]
Docker would help in certain aspects, however, it would also complicate things. Currently, you can just log into your box running all these services and keep packages up-to-date regarding security fixes with a single "apt-get update; apt-get upgrade". Docker will make this more complicated.
